### PR TITLE
First steps towards BS 2.0

### PR DESCRIPTION
**Pull request by DreadPirateLynx**
Moved Force Entries from the game system file into the corresponding army files. The army lists are all usable now, although some conditions may be acting wonky with the update to 2.0. Post an issue if any army entries that were working pre 2.0 are now acting funky. I also took the liberty of moving all USRs to the game system file, and adjusted the links in all of the army files to use the new location. This was all done to make creating new army files easier in the future. The next step would be to start migrating some of the more prolific profiles/entries (power weapons, bolt weapons, etc...) into the game system file as well.

Last but not least, Harlequins have been added.

### CODE REVIEW

**Comment by DreadPirateLynx** [comment]
Been working my way through the open issues and fixing the things I have time to do.
#44, #48, #53, and #60 all fixed and can be closed once merged

**Comment by beckian** [comment]
I haven't been able to download the BS2 alpha to try out yet, I keep getting a Bandwidth Limit Exceeded error. When I do I'll be able to work on smoothing out any wonkiness from the BS2 change over. Are we still keeping a 1.15 version of the files? Or are we able to look back at the history and access the files before BS2 change over?

**Comment by DreadPirateLynx** [comment]
Hmm... It's possible to look back at the history and get old versions of files, but it's not the most straight-forward thing in the world:

Go to the Graphs tab, then the Network sub-tab.
Click on the dot that represents the commit you want to look at.
Click "Browse Files"
You're now looking at the old versions of the files, and can download them.

Alternatively, you could tag the current state of the repository as "v1.15" in the Code tab, then all anyone would have to do is click on the Branch drop down, switch to the Tags tab, and click on it there. That's probably the route I would suggest. If a lot of people aren't switching to 2.0, someone can always fork it from that point and continue developing it for 1.15.

**Comment by DreadPirateLynx** [comment]
In addition to fixing Issue #54, I also fixed some broken conditions that were causing BS to not properly update the max number of Assault Marines, Scout Bikers, and Bikers when the proper Sergeant was chosen. This was done in the SM, DA, and BA data files, but I noticed that BA is out-of-date and needs to be updated.

**Pull request merged**
